<?php

class Doublee_Fields {

	public function __construct() {
		add_action('acf/include_fields', [$this, 'register_global_settings_fields'], 5, 0);
		add_filter('acf/load_value/name=logo', [$this, 'load_classicpress_logo'], 10, 3);
		add_action('acf/save_post', [$this, 'save_classicpress_logo'], 10, 1);
	}

	public function register_global_settings_fields(): void {
		if(function_exists('acf_add_local_field_group')) {
			acf_add_local_field_group(array(
				'key'                   => 'group_5876ae3e825e9',
				'title'                 => 'Global options',
				'fields'                => array(
					array(
						'key'               => 'field_65910e84e0efd',
						'label'             => 'Brand',
						'name'              => '',
						'aria-label'        => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'left',
						'endpoint'          => 0,
						'selected'          => 0,
						'repeatable'        => true,
					),
					array(
						'key'               => 'field_65910e95e0efe',
						'label'             => 'Logo',
						'name'              => 'logo',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '65',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'id',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'preview_size'      => 'medium',
						'uploader'          => '',
						'acfe_thumbnail'    => 0,
						'repeatable'        => true,
					),
					array(
						'key'               => 'field_60e6b91c89105',
						'label'             => 'Contact details',
						'name'              => '',
						'aria-label'        => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'left',
						'endpoint'          => 0,
						'selected'          => 0,
						'repeatable'        => true,
					),
					array(
						'key'                     => 'field_60e6b78dff698',
						'label'                   => 'Contact details',
						'name'                    => 'contact_details',
						'aria-label'              => '',
						'type'                    => 'group',
						'instructions'            => '',
						'required'                => 0,
						'conditional_logic'       => 0,
						'wrapper'                 => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'                  => 'block',
						'acfe_seamless_style'     => 0,
						'acfe_group_modal'        => 0,
						'acfe_group_modal_close'  => 0,
						'acfe_group_modal_button' => '',
						'acfe_group_modal_size'   => 'large',
						'repeatable'              => true,
						'sub_fields'              => array(
							array(
								'key'               => 'field_60e6b7a1ff699',
								'label'             => 'Phone',
								'name'              => 'phone',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_60e6b7b8ff69a',
								'label'             => 'Address',
								'name'              => 'address',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_60e6b7caff69b',
								'label'             => 'Suburb',
								'name'              => 'suburb',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_60e6b7d1ff69c',
								'label'             => 'State',
								'name'              => 'state',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_60e6b7d8ff69d',
								'label'             => 'Postcode',
								'name'              => 'postcode',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_6636f261c4ba9',
								'label'             => 'Email',
								'name'              => 'email',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'repeatable'        => true,
							),
						),
					),
					array(
						'key'                           => 'field_6591102f913cb',
						'label'                         => 'Social media links',
						'name'                          => 'social_media_links',
						'aria-label'                    => '',
						'type'                          => 'repeater',
						'instructions'                  => '',
						'required'                      => 0,
						'conditional_logic'             => 0,
						'wrapper'                       => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'                        => 'table',
						'pagination'                    => 0,
						'min'                           => 0,
						'max'                           => 0,
						'collapsed'                     => '',
						'button_label'                  => 'Add link',
						'rows_per_page'                 => 20,
						'acfe_repeater_stylised_button' => 0,
						'repeatable'                    => true,
						'sub_fields'                    => array(
							array(
								'key'               => 'field_6591103c913cc',
								'label'             => 'Label',
								'name'              => 'label',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '20',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6591102f913cb',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_6591104b913cd',
								'label'             => 'Font awesome icon',
								'name'              => 'icon',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '30',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6591102f913cb',
								'repeatable'        => true,
							),
							array(
								'key'               => 'field_65911055913ce',
								'label'             => 'URL',
								'name'              => 'url',
								'aria-label'        => '',
								'type'              => 'url',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '50',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'parent_repeater'   => 'field_6591102f913cb',
								'repeatable'        => true,
							),
						),
					),
					array(
						'key'               => 'field_67144bbfa473a',
						'label'             => 'Accounts & Assets',
						'name'              => '',
						'aria-label'        => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'top',
						'endpoint'          => 0,
						'selected'          => 0,
					),
					array(
						'key'               => 'field_67144bf8a473c',
						'label'             => 'Google Maps API key',
						'name'              => 'google_maps_api_key',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6590ac197c0df',
						'label'             => 'About',
						'name'              => '',
						'aria-label'        => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'left',
						'endpoint'          => 0,
						'selected'          => 0,
						'repeatable'        => true,
					),
					array(
						'key'               => 'field_6590ab440f42e',
						'label'             => '',
						'name'              => '',
						'aria-label'        => '',
						'type'              => 'message',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => 'These settings come from the custom plugin created for your site by Double-E Design, and are designed for use with it and your custom theme. Other plugins and themes may use these settings, but compatibility is not guaranteed.',
						'new_lines'         => 'wpautop',
						'esc_html'          => 0,
						'repeatable'        => true,
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'acf-options-global-options',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'modified'              => 1740105843,
			));
		}
	}

	public function load_classicpress_logo($value, $post_id, $field) {
		// If we're in ClassicPress, sync the logo field it provides to the ACF field on load
		if (function_exists('classicpress_version') && get_option('login_custom_image_state')) {
			$image_id = get_option('login_custom_image_id');
			if($image_id) {
				$value = $image_id;
			}
		}

		return $value;
	}

	public function save_classicpress_logo($post_id): void {
		// If we're in ClassicPress and the logo is updated from the ACF options field, sync the change to the ClassicPress setting
		if ($post_id === 'options' && function_exists('classicpress_version')) {
			if(isset($_POST['acf']['field_65910e95e0efe'])) {
				$image_id = intval($_POST['acf']['field_65910e95e0efe']);
				update_option('login_custom_image_state', ($image_id ? 1 : 0));
				update_option('login_custom_image_id', $image_id);
			}
		}
	}
}
